export const ADD_TODO = 'add_todo'
export const UPDATE_TODO = 'update_todo'
export const DELETE_TODO = 'delete_todo'
export const CHECK_ALL_TODO = 'check_all_todo'
export const CLEAR_ALL_DONE = 'clear_all_done'
