export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CHECK_ALL_TODO = 'CHECK_ALL_TODO'
export const CLEAR_ALL_DONE = 'CLEAR_ALL_DONE'
